<?php $config = array (
  'STORE_NAME' => 
  array (
    'en' => 'Our Online Store!!',
    'lt' => 'dfgdfgdfg',
    'lv' => '',
    'ab' => '',
  ),
  'NUM_PRODUCTS_PER_CAT' => '10',
  'NUM_PRODUCTS_PER_SEARCH' => '10',
  'SORT_ORDER' => 'MONTHLY_RANK',
  'DISPLAY_NUM_CAT' => 1,
  'DISPLAY_NUM_FILTER' => 1,
  'DISPLAY_IMAGE_IN_LIST' => 1,
  'UNIT_SYSTEM' => 'METRIC',
  'IMG_P_SMALL_W' => '80',
  'IMG_P_SMALL_H' => '50',
  'IMG_P_SMALL_Q' => '80',
  'IMG_P_THM_W' => '120',
  'IMG_P_THM_H' => '80',
  'IMG_P_THM_Q' => '80',
  'IMG_P_MEDIUM_W' => '400',
  'IMG_P_MEDIUM_H' => '300',
  'IMG_P_MEDIUM_Q' => '80',
  'IMG_P_LARGE_W' => '800',
  'IMG_P_LARGE_H' => '600',
  'IMG_P_LARGE_Q' => '80',
  'IMG_C_SMALL_W' => '80',
  'IMG_C_SMALL_H' => '50',
  'IMG_C_SMALL_Q' => '80',
  'IMG_C_THM_W' => '120',
  'IMG_C_THM_H' => '80',
  'IMG_C_THM_Q' => '80',
  'IMG_C_MEDIUM_W' => '400',
  'IMG_C_MEDIUM_H' => '300',
  'IMG_C_MEDIUM_Q' => '80',
  'IMG_C_LARGE_W' => '800',
  'IMG_C_LARGE_H' => '600',
  'IMG_C_LARGE_Q' => '80',
  'DISABLE_INVENTORY' => 0,
  'DISABLE_NOT_IN_STOCK' => 0,
  'ANONYMOUS_CHECKOUT' => 1,
  'MIN_TOTAL' => '0',
  'MAX_TOTAL' => '0',
  'MAX_QUANT' => '0',
  'STORE_COUNTRY' => 'US',
  'STORE_STATE' => 'NY',
  'STORE_ZIP' => '10001',
  'STORE_CITY' => 'New York',
  'DEF_COUNTRY' => 'US',
  'DEF_STATE' => 'NY',
  'DEF_ZIP' => '10001',
  'DEF_CITY' => 'New York',
  'PRICE_FILTER_NAME_1' => 
  array (
    'en' => '0 to 24',
    'lt' => '',
    'lv' => '',
    'ab' => '',
  ),
  'PRICE_FILTER_FROM_1' => '0',
  'PRICE_FILTER_TO_1' => '24',
  'PRICE_FILTER_NAME_2' => 
  array (
    'en' => '25 to 49',
    'lt' => '',
    'lv' => '',
    'ab' => '',
  ),
  'PRICE_FILTER_FROM_2' => '25',
  'PRICE_FILTER_TO_2' => '49',
  'PRICE_FILTER_NAME_3' => 
  array (
    'en' => '50 to 99',
    'lt' => '',
    'lv' => '',
    'ab' => '',
  ),
  'PRICE_FILTER_FROM_3' => '50',
  'PRICE_FILTER_TO_3' => '99',
  'PRICE_FILTER_NAME_4' => 
  array (
    'en' => '100 to 199',
    'lt' => '',
    'lv' => '',
    'ab' => '',
  ),
  'PRICE_FILTER_FROM_4' => '100',
  'PRICE_FILTER_TO_4' => '199',
  'PRICE_FILTER_NAME_5' => 
  array (
    'en' => '200 to 499',
    'lt' => '',
    'lv' => '',
    'ab' => '',
  ),
  'PRICE_FILTER_FROM_5' => '200',
  'PRICE_FILTER_TO_5' => '499',
  'PRICE_FILTER_NAME_6' => 
  array (
    'en' => '500 to 999',
    'lt' => '',
    'lv' => '',
    'ab' => '',
  ),
  'PRICE_FILTER_FROM_6' => '500',
  'PRICE_FILTER_TO_6' => '999',
  'PRICE_FILTER_NAME_7' => 
  array (
    'en' => '1000 to 1999',
    'lt' => '',
    'lv' => '',
    'ab' => '',
  ),
  'PRICE_FILTER_FROM_7' => '1000',
  'PRICE_FILTER_TO_7' => '1999',
  'PRICE_FILTER_NAME_8' => 
  array (
    'en' => '2000 to 4999',
    'lt' => '',
    'lv' => '',
    'ab' => '',
  ),
  'PRICE_FILTER_FROM_8' => '2000',
  'PRICE_FILTER_TO_8' => '4999',
  'PRICE_FILTER_NAME_9' => 
  array (
    'en' => '5000 to 9999',
    'lt' => '',
    'lv' => '',
    'ab' => '',
  ),
  'PRICE_FILTER_FROM_9' => '5000',
  'PRICE_FILTER_TO_9' => '9999',
  'PRICE_FILTER_NAME_10' => 
  array (
    'en' => 'More than 10000',
    'lt' => 'Labai brangiai',
    'lv' => '',
    'ab' => '',
  ),
  'PRICE_FILTER_FROM_10' => '10000',
  'PRICE_FILTER_TO_10' => '10000000000',
  'IMG_P_W_1' => '40',
  'IMG_P_H_1' => '40',
  'IMG_P_Q_1' => '80',
  'IMG_P_W_2' => '80',
  'IMG_P_H_2' => '120',
  'IMG_P_Q_2' => '80',
  'IMG_P_W_3' => '400',
  'IMG_P_H_3' => '300',
  'IMG_P_Q_3' => '80',
  'IMG_P_W_4' => '800',
  'IMG_P_H_4' => '600',
  'IMG_P_Q_4' => '80',
  'IMG_C_W_1' => '80',
  'IMG_C_H_1' => '50',
  'IMG_C_Q_1' => '80',
  'IMG_C_W_2' => '120',
  'IMG_C_H_2' => '80',
  'IMG_C_Q_2' => '80',
  'IMG_C_W_3' => '400',
  'IMG_C_H_3' => '300',
  'IMG_C_Q_3' => '80',
  'IMG_C_W_4' => '800',
  'IMG_C_H_4' => '600',
  'IMG_C_Q_4' => '80',
  'MAX_FILTER_CRITERIA_COUNT' => '5',
); ?>