ALTER TABLE EavField ADD CONSTRAINT EavFieldGroup_EavField
    FOREIGN KEY (eavFieldGroupID) REFERENCES EavFieldGroup (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE EavObject ADD CONSTRAINT Category_EavObject
    FOREIGN KEY (categoryID) REFERENCES Category (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE EavObject ADD CONSTRAINT User_EavObject
    FOREIGN KEY (userID) REFERENCES User (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE EavObject ADD CONSTRAINT UserGroup_EavObject
    FOREIGN KEY (userGroupID) REFERENCES UserGroup (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE EavObject ADD CONSTRAINT Manufacturer_EavObject
    FOREIGN KEY (manufacturerID) REFERENCES Manufacturer (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE EavObject ADD CONSTRAINT CustomerOrder_EavObject
    FOREIGN KEY (customerOrderID) REFERENCES CustomerOrder (ID) ON DELETE CASCADE ON UPDATE CASCADE;
